name: multitool_app
description: "A new Flutter project."

publish_to: 'none' 



environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.0
  http: ^1.4.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  lottie: ^3.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  assets:
    - lib/assets/
    - .env